//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishakov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ratings
    {
        public int ID { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<int> Items_id { get; set; }
        public Nullable<int> Evaluation { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Student Student { get; set; }
    }
}
